### ISSUE TITLE
images links broken

### ISSUE THREAD

**Issue by seven1240** [kamailio/kamailio-wiki#11]
https://www.kamailio.org/wikidocs/cookbooks/devel/pseudovariables/

there's a pseudovariables.png in the same folder as the `.md` but the generated doc has a trailing slash, should we move it to a sub folder? then it will break the display on https://github.com/kamailio/kamailio-wiki/blob/main/docs/cookbooks/devel/pseudovariables.md

or maybe create a symbol link?

**Comment by miconda** [comment]
Apparently using the html `img` tag is creating the issue, even it is valid to use in markdown, but probably mkdocs has issues updating it.

Using the markdown `![img](img)` solves it, but lacks support for alignment (the html variant was aligned to right).

Anyhow, I don't think that image adds much value, not being a diagram or some explanatory content, so it can be removed.
