### ISSUE TITLE
#!KAMAILIO compatibility mode is not documented

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio-wiki#30]
The meaning of `#!KAMAILIO` in the configuration file is nowhere documented, in particular it is not in the core cookbook It is mentioned only at https://www.kamailio.org/docs/modules/devel/modules/tm.html#tm.p.fr_timer_avp and in misc/NEWS under sip-router 3.0 changes → config script changes.

To be honest, I have deleted `#!KAMAILIO` from my configuration file, since the lack of documentation for this directive implied to me, that `#!KAMAILIO` does nothing.

Please document what #!KAMAILIO does and at best make it the default.

**Comment by henningw** [comment]
I think the #°KAMAILIO is actually the default. This is another legacy option from the merge from the sip-router project. It might be also a good idea to just remove it from the code.

**Comment by miconda** [comment]
Added section in the core cookbook about compatibility modes.
